config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :charges

  devise_for :users
  get 'home/index'
  root 'home#index'
  get '/searches' => 'searches#index'
  post '/searches' => 'searches#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json

  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :avatar, :language, :age, :location, :number_of_students, :gender, :bio)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    if params[:search]
      @profiles = Profile.where("lower(language) LIKE ?", "%#{params[:search].downcase}")
    else
      @profiles = Profile.all
    end
  end

#
#   # GET /searches/1
#   # GET /searches/1.json
#   def show
#   end
#
#   # GET /searches/new
#   def new
#     @search = Search.new
#   end
#
#   # GET /searches/1/edit
#   def edit
#   end
#
#   # POST /searches
#   # POST /searches.json
#   def create
#     @search = Search.new(search_params)
#
#     respond_to do |format|
#       if @search.save
#         format.html { redirect_to @search, notice: 'Search was successfully created.' }
#         format.json { render :show, status: :created, location: @search }
#       else
#         format.html { render :new }
#         format.json { render json: @search.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /searches/1
#   # PATCH/PUT /searches/1.json
#   def update
#     respond_to do |format|
#       if @search.update(search_params)
#         format.html { redirect_to @search, notice: 'Search was successfully updated.' }
#         format.json { render :show, status: :ok, location: @search }
#       else
#         format.html { render :edit }
#         format.json { render json: @search.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /searches/1
#   # DELETE /searches/1.json
#   def destroy
#     @search.destroy
#     respond_to do |format|
#       format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_search
#       @search = Search.find(params[:id])
#     end
#
#     # Never trust parameters from the scary internet, only allow the white list through.
#     def search_params
#       params.fetch(:search, {})
#     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/charges/create.html.erb
<h2>Thanks for your payment</h2>

<%= link_to 'Profiles', profiles_path, class: 'btn btn-group btn-info' %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<h1>ESL Penpal App</h1>

<h4>About</h4>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<div id="map"></div>
    <script>
    var map;
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: -34.397, lng: 150.644},
        zoom: 8
  });
}
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API"] %>&callback=initMap"
    async defer>
    </script>
</div>
<br>
<%= link_to 'View Penpals', profiles_path, class: 'btn btn-lg btn-primary' %>

<%= link_to 'Contact Us', '#', class: 'btn btn-lg btn-success' %>

<%= link_to 'Search Profiles', searches_path, class: 'btn btn-lg btn-warning' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ESL Penpal App</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>
              </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<!-- Code to use for navbar once I have signin working -->

<!-- <nav class= "navbar navbar-default"> -->

<%#= if user.signed_in? %>
  <%#= render 'Signed in as #{current_user}', class: 'navbar-text' %>
<%# else %>
  <%#= link_to 'Login', new_user_session, :class 'btn btn-default navbar-btn' %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eslpenapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render 'layouts/navbar' %>
    <%= yield %>

</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>

  <br>

</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :avatar, label: 'Upload a class photo' %>

    <%= f.input :language, label: 'What is their native language?', required: true %>

    <%= f.input :age, label: 'What is the average age of the class?', required: true %>

    <%= f.input :location, label: 'What country is the class located in?' %>

    <%= f.input :number_of_students, label: 'How many students are in the class?', required: true %>

    <%= f.input :gender, label: 'What gender is the class? (Male/Female/Mixed)', collection: [:male, :female, :mixed] %>

    <%= f.input :bio, input_html: {maxlength: 600}, label: 'Tell us about your class (600 characters maximum)' %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-info' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Class Picture</th>
      <th>Class Language</th>
      <th>Average Age</th>
      <th>Class Location</th>
      <th>Number of Students</th>
      <th>Class Gender</th>
      <th>About the Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>

        <td>
          <img src="<%= profile.avatar_url.to_s %>" width="25%">
        </td>

        <td>
          <%= profile.language %>
        </td>

        <td>
          <%= profile.age %>
        </td>

        <td>
          <%= profile.location %>
        </td>

        <td>
          <%= profile.number_of_students %>
        </td>

        <td>
          <%= profile.gender %>
        </td>

        <td>
          <%= truncate(profile.bio, :length => 50) %>
        </td>

        <td>
          <%= link_to 'Show', profile, class: 'btn btn-xs btn-info' %>
        </td>

        <td>
          <%= link_to 'Edit', edit_profile_path(profile), class: 'btn btn-xs btn-success' %>
        </td>

        <td>
          <%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New subscription', new_charge_path, class: 'btn btn-group btn-default' %>
<%= link_to 'Search Profiles', searches_path, class: 'btn btn-group btn-warning' %>
<%= link_to 'Create a Profile', new_profile_path, class: 'btn btn-group btn-info' %>
<%= link_to 'Main Page', home_index_path, class: 'btn btn-primary btn-group' %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <img src="<%= @profile.avatar_url.to_s if @profile.avatar_url.present? %>" width="75%" height="75%">
</p>

<p>
  <strong>Language:</strong>
  <%= @profile.language %>
</p>

<p>
  <strong>Average Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>

<p>
  <strong>Number of Students</strong>
  <%= @profile.number_of_students %>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/searches/_form.html.erb
<%= simple_form_for :search, url: profiles_path  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%=f.input :search, input_html: { value: @search['search']} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, label: 'search', class: 'btn btn-lg btn-info' %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Profiles', profiles_path %>

<h1>Listing Searches</h1>

<%= form_tag :method => 'GET' %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search' %>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Location</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag profile.avatar,  width: '32' %></td>
        <td><%= profile.language %></td>
        <td><%= link_to 'Show', profile %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', profiles_path, class: 'btn btn-lg btn-primary' %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>